name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ZeroTierOne
        uses: actions/checkout@v3
        with:
          repository: "zerotier/ZeroTierOne"
          path: "ZeroTierOne"
          ref: "dev"
      - name: Checkout ZeroTierFix
        uses: actions/checkout@v3
        with:
          repository: "kaaass/ZerotierFix"
          path: "ZerotierFix"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "ZeroTierFix-Build"
      - name: Prehandle ZeroTierFix
        run: |
          export version=$(curl "https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest" | jq -r '.name')
          export ver=${version//./}
          cd ZerotierFix
          cd app
          sed -r -i "s/versionName \"(.*?)_.*\"/versionName \"\1_$ver\"/g" build.gradle
          cd src
          cd main
          cd java
          rm -rf com/
          cd ../
          rm -rf jniLibs
          cd ../../../../
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
      - name: Compile ZeroTier Core & Move Files to ZerotierFix
        env:
          CMAKE_TOOLCHAIN_FILE: ${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake
          SDK: android-17
        run: |
          cd ZeroTierOne/java
          rm CMakeLists.txt
          cp ../../ZeroTierFix-Build/CMakeLists.txt .
          mkdir jniLibs
          mkdir jniLibs/armeabi-v7a
          cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=$SDK
          make
          rm CMakeFiles/ -rf
          mv libZeroTierOneJNI.so jniLibs/armeabi-v7a/
          mkdir jniLibs/arm64-v8a
          cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=$SDK
          make
          rm CMakeFiles/ -rf
          mv libZeroTierOneJNI.so jniLibs/arm64-v8a/
          mkdir jniLibs/x86
          cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DANDROID_ABI=x86 -DANDROID_PLATFORM=$SDK
          make
          rm CMakeFiles/ -rf
          mv libZeroTierOneJNI.so jniLibs/x86/
          mkdir jniLibs/x86_64
          cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=$SDK
          make
          rm CMakeFiles/ -rf
          mv libZeroTierOneJNI.so jniLibs/x86_64
          cd src
          mv com/ ../../../ZerotierFix/app/src/main/java/
          cd ..
          mv jniLibs/ ../../ZerotierFix/app/src/main/
          cd ..
          cd ..
          rm -rf ZeroTierOne
      - name: Build APK
        uses: anime-vsub/android-build-action@1.2.1
        with:
          project-path: ZerotierFix
          output-path: ZerotierFix-Debug.apk
          gradle-task: assemble
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ZerotierFix-Build
          path: ZerotierFix-Debug.apk
