name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ZeroTierOne
        uses: actions/checkout@v3
        with:
          repository: "zerotier/ZeroTierOne"
          path: "ZeroTierOne"
          ref: "dev"
      - name: Checkout ZeroTierFix
        uses: actions/checkout@v3
        with:
          repository: "kaaass/ZerotierFix"
          path: "ZerotierFix"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "ZeroTierFix-Build"
      - name: Prehandle ZeroTierFix
        run: |
          export version=$(curl "https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest" | jq -r '.name')
          export ver=${version//./}
          echo "corever=$ver" >> $GITHUB_ENV
          cd ZerotierFix/app
          sed -r -i "s/versionName \"([^_]*?)_.*\"/versionName \"\1_$ver\"/g" build.gradle
          cd src
          cd main
          cd java
          rm -rf com/
          cd ../
          rm -rf jniLibs
          cd ../../../../
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
      - name: Compile ZeroTier Core & Move Files to ZerotierFix
        env:
          CMAKE_TOOLCHAIN_FILE: ${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake
          SDK: android-19
        run: |
          cd ZeroTierOne/java
          rm CMakeLists.txt
          cp ../../ZeroTierFix-Build/CMakeLists.txt .
          mkdir jniLibs
          for ABI in "armeabi-v7a" "arm64-v8a" "x86" "x86_64"
          do
            mkdir jniLibs/$ABI
            cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DANDROID_ABI=$ABI -DANDROID_PLATFORM=$SDK
            make
            rm CMakeFiles/ -rf
            mv libZeroTierOneJNI.so jniLibs/$ABI/
          done
          cd src
          mv com/ ../../../ZerotierFix/app/src/main/java/
          cd ..
          cp -r jniLibs/ ../../
          mv jniLibs/ ../../ZerotierFix/app/src/main/
          cd ..
          cd ..
          rm -rf ZeroTierOne
      - name: Upload jniLibs
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.corever }}-jniLibs
          path: jniLibs/
      - name: Build APK
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: ZerotierFix
          output-path: ZerotierFix-${{ env.corever }}.apk
          gradle-task: assemble
      - name: Sign APK
        id: sign_app
        uses: noriban/sign-android-release@v3
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: ZerotierFix-${{ env.corever }}
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
