name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ZeroTierFix
        uses: actions/checkout@v3
        with:
          repository: "kaaass/ZerotierFix"
          path: "ZerotierFix"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "ZeroTierFix-Build"
      - name: Prehandle ZeroTierFix
        run: |
          export version=$(curl "https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest" | jq -r '.name')
          export ver=${version//./}
          echo "corever=$ver" >> $GITHUB_ENV
          cd ZerotierFix/app
          sed -r -i "s/versionName \"(.*?)\"/versionName \"\1_$ver\"/g" build.gradle
          cd ..
          rm -rf externals
          mkdir externals
      - name: Checkout ZeroTierOne
        uses: actions/checkout@v3
        with:
          repository: "zerotier/ZeroTierOne"
          path: "ZerotierFix/externals/core"
          ref: "dev"
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
      - name: Do something else
        run: |
          cd ZerotierFix/externals/core/java
          rm CMakeLists.txt
          cp ../../../../ZeroTierFix-Build/CMakeLists.txt .
          cd ../../../../
      - name: Build APK
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: ZerotierFix
          output-path: ZerotierFix-${{ env.corever }}.apk
          gradle-task: assemble
      - name: Sign APK
        id: sign_app
        uses: noriban/sign-android-release@v3
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: ZerotierFix-${{ env.corever }}
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
